// remote-app/src/App.jsx
import reactLogo from './assets/react.svg'
import './App.css'
import Button from './components/Button'
import viteLogo from '../public/vite.svg'

function App() {

  return (
    <div className="App">
      <h1>REMOTE APP</h1>
      <div className='stack'>
        <h2>Stack: </h2>
        <img src={viteLogo} className="logo" alt="Vite logo" />
        <img src={reactLogo} className="logo react" alt="React logo" />
      </div>
      <div className="card">
        <Button />
      </div>
    </div>
  )
}

export default App

// remote-solid/src/App.jsx
import solidLogo from './assets/logo.svg';
import viteLogo from '/vite.svg'
import styles from './App.module.css';
import { createSignal } from 'solid-js';

function App() {
  const [count, setCount] = createSignal(0)
  return (
    <div class={styles.App}>
      <h1>REMOTE APP</h1>
      <div className={styles.stack}>
        <h2>Stack: </h2>
        <img src={viteLogo} class={styles.logo} alt="vite logo" />
        <img src={solidLogo} class={styles.logo} alt="solid logo" />
      </div>
      <main>
        <button onClick={() => {
          setCount(count() + 1)
        }}>count is {count()}</button>
      </main>
    </div>
  );
}

export default App;
